package.json
Couldn't get webpack to work correctly, so we're going with a simpler Babel conversion instead for the time being.
=> changed export strategy to a simple babel conversion instead of webpack

src/immutables/Auth.js, src/importers/cURL/Parser.js, src/importers/swagger/Parser.js, src/importers/swagger/__tests__/fixtures/Parser-fixtures.js
Don't mind the small change to the cURL Parser.
Added a `scopes` field in the OAuth2 representation.
Implemented scopes support in the Swagger importer.
Updated tests to account for scopes in OAuth2
=> Added Scope support to API-flow for OAuth2

src/importers/cURL/Parser.js, src/importers/cURL/__tests__/Parser-test.js
Currently, the cURL importer only relies on urlEncoded and formData body types, and therefore supercharges the urlEncoded body type with json, plain, and file type. 
This PR aims at refactoring the body types into these different blocks:
- urlEncoded
- formData
- plain
- json
- file
- schema (not used in cURL importer)
=> Enhance curl importer body types

package.json, src/index.js
Bumped version to 0.0.6
Added the Parsers to the public interface of api-flow
=> prepublish to npm cleanup (v0.0.6)

src/immutables/RequestContext.js, src/importers/swagger/Parser.js, src/importers/swagger/__tests__/Parser-test.js, src/utils/TestUtils.js
This PR fixes the propagation issue for parameters.
Fixes [issue#34](https://github.com/luckymarmot/API-Flow/issues/34)
Also fixes List support in `Schema` objects. Before, a list in a schema would be converted to an object with keys [0, 1, 2, 3, ...], when calling `schema.toJS()`. It is now correctly converted back to an array.
=> 037 fix swagger global parameters

src/parsers/postman/v1/Parser.js
this should fix an issue with the postman importer around corrupted digest auth data in the header field (when no helper is present)
=> Postman Digest Auth Bugfix

Makefile, src/parsers/cURL/Parser.js, src/parsers/cURL/__tests__/Parser-test.js
I changed the way cURL stores body variables.
If a body parameter was a string instead of a key-value pair, It used to store the variable data in the `key` field of the parameter instead of the `data` field, which was not in line with the expected behavior from parsers.
it now correctly stores it in the `data` field.
=> 059 improve body curl

src/parsers/paw/Parser.js
fixed a bug where the PAW serializer grouped all the content of environment variables into a single uri component
=> Fix EnvironmentVariables being put in single URI component

src/parsers/cURL/Parser.js, src/serializers/paw/base-importer/BaseImporter.js
Documents containing a single request will not be imported in a sub group used for grouping.
You can still insert in any position in any group.
Also partial fixes a bug with the curl importer
=> 074 single request

src/parsers/postman/v1/Parser.js, src/serializers/paw/base-importer/BaseImporter.js
Fixed multiple bugs around environments in the Postman Parser + Paw Serializer.
- Now correctly imports auto generated environments when no environment is available
- DynamicStrings that should have contained a single component referencing an environment variable from Postman now correctly references to it, instead of returning an empty string.
Also fixes a bug where we would infer a `multipart/form-data` or `application/x-www-form-urlencoded` from the request if the request had no `Content-Type`, but also no body to send. Now only does this when there's a body to send.
=> 079 postman placeholder

src/parsers/postman/v2/Parser.js, src/parsers/swagger/Parser.js
* an undefined body in a request in a v2 collection caused the app to crash (postman)
* the `/` basePath was not properly trimmed (swagger)
=> Postman collection v2 parser & Swagger parser bugfix 

src/parsers/paw/Parser.js, src/serializers/raml/Serializer.js, src/serializers/swagger/Serializer.js, src/serializers/swagger/__tests__/Serializer-test.js
Fixes an issue around an undocumented behavior of `request.getUrlEncodedBody(true)` in case of multiple parameters
Improves duplicate handling for swagger and RAML
=> 085 - Fixes for duplicate params

src/parsers/paw/Parser.js, src/parsers/raml/v0.8/Parser.js, src/runners/flow-webworker.js, src/serializers/postman/Serializer.js, src/serializers/swagger/Serializer.js
- Fixed a bug where the Content-Type would not be taken into account when the body was not a url-encoded or multipart
- Paw parser now uses an Immutable.List for OAuth2 scopes - like they should be
- `let => const` for a bunch of expressions
- normalized the error thrown by the RAML loader in the RAML Parser (ScannerError were very verbose)
- fixed a bug where postman serializer would crash on local JSON Schemas (usually happened when converting from Swagger to Postman)
- fixed the postman serializer type to actually match the definition in the postman 1.0 schema
- Swagger serializer is now more tolerant towards OAuth2 scopes (can be Array or Immutable.List),. Although scopes should still be an Immutable.List, this should protect the serializer against poor implementations.
=> 088 All Around Bug Fixes

src/parsers/internal/Parser.js, src/runners/base-runner.js, src/runners/flow-web.js, src/serializers/postman/Serializer.js
- improves postman serializers handling of headers (removes a `\nundefined` that appeared in some instances)
- improves handling of the body in the case where it is a JSONSchemaReference that's an inline reference, whose schema is of type `string` and has a `default` field. We now store the generated value of the schema (e.g. the `default` value), instead of the schema. Behavior fits better most cases.
- **InternalParser:** fixed a typo for the internal parser
- **base-runner:** added a check for options in `parse` as this method is now public and can be used with a simple object instead of an `Options` immutable record.
- **flow-web:** added the internal parser and made FlowBrowser a non-default export so that it can be accessible from window via this name.
=> Postman Serializer - body generation issue & Internal Parser bug fixes

src/models/Auth.js, src/parsers/raml/v0.8/Parser.js, src/parsers/raml/v0.8/__tests__/Parser-test.js, src/parsers/swagger/v2.0/Parser.js, src/parsers/swagger/v2.0/__tests__/Parser-test.js, src/parsers/swagger/v2.0/__tests__/fixtures/Parser-fixtures.js, src/resolvers/__tests__/ParameterResolver-test.js
- adds `authName` to auth model
- adds auth naming support to swagger parser
- adds auth naming support to raml parser
=> Add Names to Auths

src/models/Auth.js, src/models/Core.js, src/parsers/cURL/Parser.js, src/parsers/cURL/__tests__/Parser-test.js, src/parsers/internal/Parser.js, src/parsers/paw/Parser.js, src/parsers/paw/__tests__/Parser-test.js, src/parsers/postman/v1/Parser.js, src/parsers/postman/v1/__tests__/Parser-test.js, src/parsers/postman/v2/Parser.js, src/parsers/raml/resolvers/FileResolver.js, src/parsers/raml/resolvers/HttpResolver.js, src/parsers/raml/resolvers/__tests__/FileResolver-test.js, src/parsers/raml/v0.8/Parser.js, src/parsers/raml/v0.8/__tests__/Parser-test.js, src/parsers/raml/v1.0/Parser.js, src/parsers/swagger/v2.0/Parser.js, src/parsers/swagger/v2.0/__tests__/Parser-test.js, src/parsers/swagger/v2.0/__tests__/fixtures/Parser-fixtures.js, src/resolvers/__tests__/ParameterResolver-test.js, src/serializers/cURL/Serializer.js, src/serializers/paw/Serializer.js, src/serializers/paw/__tests__/fixtures/Serializer-fixtures.js, src/serializers/postman/Serializer.js, src/serializers/raml/Serializer.js, src/serializers/raml/__tests__/Serializer-test.js, src/serializers/swagger/Serializer.js
- Adds a field `requests` to the `Context` object. the `requests` field is an `Immutable.OrderedMap<uuid,Request>` object
- Removes `Request` objects from groups. `uuids` are used instead that link the children to the locations in the groups.
- All parsers have been updated to match the new model
- All serializers have been updated to match the new model
=> 097 separate groups from requests

src/parsers/paw/Parser.js, src/parsers/paw/dv/DVManager.js, src/parsers/paw/dv/DynamicValueConverter.js, src/parsers/paw/dv/EnvironmentVariable.js, src/parsers/paw/dv/__tests__/EnvironmentVariable-test.js, src/serializers/paw/Serializer.js, src/serializers/paw/__tests__/Serializer-test.js
- Paw Parser now supports default values for reference parameters
- Updated DVManager to call convert after instantiation rather than during instantiation of DV
- Refactored EnvironmentVariable DV to be easily testable and more readable
- Added tests for EnvironmentVariable
- Refactored Paw Serializer handling of errors in promise, so that the tests would not use the default `console.error` behavior
- Added tests for the Error Handling in Paw Serializer
=> improved paw parser management of environment variables

package.json
JSF 0.3.7 implementation is much more robust than JSF 0.3.1
=> upgrade json schema faker version to 0.3.7

src/mocks/PawMocks.js, src/mocks/PawShims.js, src/models/environments/PawEnvironment.js, src/models/environments/__tests__/PawEnvironment-test.js, src/parsers/raml/FileReader.js, src/parsers/raml/v0.8/Parser.js, src/parsers/raml/v0.8/__tests__/Parser-test.js, src/runners/paw-importer/raml/Importer.js
- added NetworkHttpRequest mock and shim
- PawEnvironment URLResolver can now resolve urls
- RAMLParser now exposes a `setFileReader` method that can be used to update the fileReader with the correct context (items and urlResolver)
- RAMLImporter now sets it RAMLParser's fileReader using the `setFileReader` method
=> 106 improve raml file resolution

configs/paw/importers/postman2/api-flow-config.js, configs/paw/importers/postman2/webpack.config.babel.js, src/environments/paw/Environment.js, src/loaders/postman/v2.0/Loader.js, src/loaders/postman/v2.0/__tests__/Loader.spec.js, src/parsers/postman/v2.0/Parser.js, src/parsers/postman/v2.0/__tests__/Parser.spec.js
=> 126 postman 2 parser
